service: endpoint-station-auth
plugins:
  - serverless-domain-manager
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7
functions:
  login:
    handler: auth.login
    events:
            - http:
                    path: login
                    method: get
  verify:
    handler: auth.verify
    events:
            - http:
                    path: verify
                    method: get
                    request:
                            parameters:
                                    querystrings:
                                            code: true
custom:
        customDomain:
                domainName: 'endpointstation.marioleone.me'
                basePath: 'auth'
        pythonRequirements:
                pythonBin: '/usr/bin/python3'
