service: endpoint-station-stations
plugins:
  - serverless-domain-manager
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7
functions:
  users:
    handler: stations.get
    events:
            - http:
                    path: ''
                    method: get
                    authorizer:
                            arn: arn:aws:cognito-idp:us-east-1:438693460185:userpool/us-east-1_7xysWBfdu
custom:
        customDomain:
                domainName: 'endpointstation.marioleone.me'
                basePath: 'stations'
                certificateArn: 'arn:aws:acm:us-east-1:438693460185:certificate/e0393115-7a0c-4b71-b8df-2e4179303625'
        pythonRequirements:
                pythonBin: '/usr/bin/python3'

